services:
  postgres:
    container_name: pg
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data

